/**
 * Cipher Detective — all user-facing text, in four languages (pl, en, uk, vi).
 * Classic script loaded after engine.js; registers one dictionary per language in ENGINE.TEXT.
 *
 * Each dictionary: { levels, guide, ciphers, whyNot, params, game, sheet }.
 *
 * The language of the texts and the language of the secret message (its alphabet) can differ,
 * so every text that names letters or counts is a function of the message alphabet `A`
 * ({ n, half, letters, idx(ch), at(i) }): cipher name/blurb/how/spot, hints(params, ex, A),
 * explain(params, ex, A), game.magnote(A), game.guideSteps(A), sheet.instrSteps(A),
 * sheet.checklist(A). `ex` is the first letter pair of the puzzle { p, c, pn, cn }.
 * Alphabets: en 26 letters (half 13) · pl 32 (16) · uk 33 (16) · vi 29 (14).
 */
(function (E) {
  const T = E.TEXT;
  const mod = (n, m) => ((n % m) + m) % m;
  const nums = (key, A) => [...key].map(A.idx).join(', ');
  const k0 = key => [...key][0];
  const L = (A, i) => A.letters[i];                       // i-th letter
  const last = (A, i = 0) => A.letters[A.n - 1 - i];      // last, 2nd-last …
  const even = A => A.n % 2 === 0;
  const mir = (A, i) => `${L(A, i)} ↔ ${last(A, i)}`;     // mirror pair for Atbash
  const mir3 = A => `${mir(A, 0)}, ${mir(A, 1)}, ${mir(A, 2)}`;
  const rot = A => `ROT${A.half}`;
  const rotPair = A => { const ar = even(A) ? '↔' : '→'; return `${L(A, 0)} ${ar} ${A.at(A.half)}, ${L(A, 1)} ${ar} ${A.at(A.half + 1)}`; };
  const numbering = A => `${L(A, 0)}=0, ${L(A, 1)}=1 … ${last(A)}=${A.n - 1}`;
  const range = A => `${L(A, 0)}=0 … ${last(A)}=${A.n - 1}`;
  /** Polish/Ukrainian plural: one (1), few (2–4 except 12–14), many (rest). */
  const slav = (n, one, few, many) => { const m10 = n % 10, m100 = n % 100; if (n === 1) return one; if (m10 >= 2 && m10 <= 4 && !(m100 >= 12 && m100 <= 14)) return few; return many; };

  /* ======================================================================== EN */
  T.en = {
    levels: { easy: 'Easy', hard: 'Hard' },
    guide: { sample: 'HELLO SPY', key: 'KEY' },
    ciphers: {
      caesar: {
        name: 'Caesar', full: 'Caesar',
        blurb: 'Every letter slides the same number of steps.',
        how: A => `Pick a number (the shift). Move every letter that many steps forward in the alphabet. After ${last(A)}, wrap around to ${L(A, 0)}.`,
        spot: A => `All the step numbers are the same — but not ${A.half} (${A.half} is ${rot(A)}).`,
        hints: ({ shift }, ex) => [
          'Look at the first letter. Count how many steps it moved forward in the alphabet. Now check the next letter — is it the same number?',
          `Every letter moved exactly ${shift} steps forward. ${ex.p} became ${ex.c}.`],
        explain: ({ shift }, ex) => `This was a Caesar cipher with a shift of ${shift}, so ${ex.p} became ${ex.c}. Every letter moved the same ${shift} steps.`,
      },
      rot13: {
        name: A => rot(A), full: A => rot(A),
        blurb: A => `Every letter moves ${A.half} steps — ${even(A) ? '' : 'almost '}half the alphabet.`,
        how: A => `A Caesar cipher with a shift of exactly ${A.half}. ${even(A) ? `Because ${A.half} is half of ${A.n}, doing it twice brings every letter back.` : `That is about half of the ${A.n} letters.`}`,
        spot: A => `Every step number is ${A.half}. ${rotPair(A)}.`,
        hints: (_, ex, A) => [
          'Every letter moved the same number of steps. Is it a big jump — about half the alphabet?',
          `Every letter moved ${A.half} steps, ${even(A) ? 'exactly' : 'almost'} half of the alphabet. ${ex.p} became ${ex.c}.${even(A) ? ` Move ${A.half} more and you are back!` : ''}`],
        explain: (_, ex, A) => `This was ${rot(A)}: every letter moved ${A.half} steps, ${even(A) ? '' : 'almost '}half the alphabet, so ${ex.p} became ${ex.c}.${even(A) ? ' Doing it twice brings the letter back.' : ''}`,
      },
      atbash: {
        name: 'Atbash', full: 'Atbash',
        blurb: A => `The alphabet is flipped: ${mir(A, 0)}, ${mir(A, 1)}.`,
        how: A => `Write the alphabet forwards, and backwards underneath. Each letter becomes the one below it: ${mir3(A)}.`,
        spot: A => `The step numbers are different, but the letter and its code letter are mirror images: the 1st letter (${L(A, 0)}) becomes the last (${last(A)}), the 2nd (${L(A, 1)}) becomes the 2nd-last (${last(A, 1)}).`,
        hints: (_, ex, A) => [
          `Try reading the alphabet backwards. What would ${L(A, 0)} turn into?`,
          `The alphabet is mirrored: ${mir3(A)}. Here ${ex.p} became ${ex.c}.`],
        explain: (_, ex, A) => `This was Atbash: the alphabet is flipped, so ${mir(A, 0)} and ${mir(A, 1)}. Here ${ex.p} became ${ex.c}.`,
      },
      vigenere: {
        name: 'Vigenère', full: 'Vigenère',
        blurb: 'A key word gives each letter its own shift, repeating.',
        how: A => `Choose a key word. Its letters are shifts (${numbering(A)}). The 1st message letter moves by the 1st key letter, the 2nd by the 2nd, and the key repeats.`,
        spot: 'The step numbers repeat in a short cycle of 3 or 4.',
        hints: ({ key }, ex, A) => [
          'The steps change from letter to letter. But look closely — do they come back around and repeat?',
          `The steps repeat every ${[...key].length} letters: ${nums(key, A)}. That is the key word ${key} added to the message.`],
        explain: ({ key }, ex, A) => `This was a Vigenère cipher with the key word ${key}. Each letter moves by its key letter: ${ex.p} + ${k0(key)} (${A.idx(k0(key))} steps) → ${ex.c}. The key repeats every ${[...key].length} letters.`,
      },
      affine: {
        name: 'Affine', full: 'Affine',
        blurb: 'Each letter number is multiplied, then shifted.',
        how: A => `Turn the letter into a number (${range(A)}). Multiply by a, add b, and wrap around ${A.n}. Turn the number back into a letter.`,
        spot: 'The same letter always becomes the same code letter, but the step numbers jump around with no cycle and no mirror.',
        hints: ({ a, b }, ex, A) => [
          'The same letter always turns into the same code letter — but the steps jump around with no cycle.',
          `Each letter's number (${range(A)}) was multiplied by ${a}, then ${b} was added.`],
        explain: ({ a, b }, ex, A) => `This was an Affine cipher: each letter's number was multiplied by ${a}, then ${b} was added. ${ex.p} is ${ex.pn}: ${a} × ${ex.pn} + ${b} = ${a * ex.pn + b}, wrap around ${A.n} → ${mod(a * ex.pn + b, A.n)}, which is ${ex.c}.`,
      },
      beaufort: {
        name: 'Beaufort', full: 'Beaufort',
        blurb: 'A key word, but you count backwards from the key letter.',
        how: A => `Choose a key word. For each message letter, start at the key letter and count backwards by the message letter's number (${L(A, 0)}=0, ${L(A, 1)}=1 …). The key repeats.`,
        spot: 'The same letter can become different code letters, and the step numbers do not repeat in a cycle.',
        hints: ({ key }) => [
          'There is a key word here — but the letters count backwards from the key, not forwards.',
          `The key word is ${key}. Each code letter = key letter − message letter (count backwards, wrapping around).`],
        explain: ({ key }, ex, A) => `This was a Beaufort cipher with the key word ${key}. Count backwards from the key letter: ${k0(key)} (${A.idx(k0(key))}) − ${ex.p} (${ex.pn}) = ${mod(A.idx(k0(key)) - ex.pn, A.n)}, which is ${ex.c}.`,
      },
    },
    whyNot: {
      closeRot13: half => `So close! ROT${half} is a special Caesar that moves exactly ${half} steps — in this game it counts as its own cipher.`,
      closeCaesar: (s, half) => `Close! Every letter did move the same number of steps — but it was ${s}, not ${half}.`,
      stepsDiffer: (g, a, b) => `It was not ${g}: the steps are not all the same. ${a.p}→${a.c} is ${a.s} steps, but ${b.p}→${b.c} is ${b.s}.`,
      notMirror: (p, m, c) => `It was not Atbash: in Atbash ${p} would become ${m}, but here it became ${c}.`,
      sameLetterDiff: (g, p, c1, c2) => `It was not ${g}: the same letter ${p} turned into ${c1} one time and ${c2} another time. That only happens with a key word.`,
      sameShift: (g, s, affine) => `It was not ${g}: every letter moved the same ${s} steps. ${affine ? 'Affine steps jump around.' : 'A key word would make the steps change.'}`,
      mirrored: g => `It was not ${g}: every letter and its code letter are mirror images (first ↔ last letter of the alphabet). That is the Atbash pattern.`,
      monoClue: 'Clue: here every letter always became the same code letter — a sign that there was no changing key word.',
      cycle: (n, ns) => `It was not Beaufort: the steps repeat in a cycle of ${n} (${ns}). That is a key word added forwards — Vigenère.`,
      noCycle: 'It was not Vigenère: the steps do not repeat in a cycle. With a key word added forwards they would.',
      keyFallback: (g, key) => `It was not ${g}: this code used the key word ${key}, so the steps follow the key.`,
    },
    params: { shift: s => `shift ${s}`, key: k => `key ${k}`, affine: (a, b) => `a = ${a}, b = ${b}` },
    game: {
      allPuzzles: '🧩 All puzzles', printWorksheet: '🖨️ Print worksheet',
      starsTitle: 'Total stars', streakTitle: 'Current streak',
      msgLang: 'Message language:',
      caseTitle: n => `Case #${n}`,
      lead: 'A spy sent this message in code. Compare the message with the code and work out which cipher was used.',
      legendMessage: 'Message', legendCode: 'In code', legendMag: '🔍 Steps each letter moved',
      magnote: A => `Numbers show how many steps each letter moved forward (${L(A, 0)}→${L(A, 1)} is 1, wrapping around after ${last(A)}).`,
      hintBtn: n => `💡 Hint (${n} left)`, noHints: '💡 No hints left', magnifier: '🔍 Magnifier', guide: '📖 Cipher guide',
      alphabet: '🔤 Alphabet', alphaNote: 'Tap a letter in the message to see its jump on the alphabet.',
      alphaJump: (p, c, s) => `${p} → ${c}: ${s} step${s === 1 ? '' : 's'} forward`,
      hintLabel: i => `💡 Hint ${i}:`,
      whichCipher: 'Which cipher was used?',
      correct: (full, cheer) => `🎉 Correct! It was ${full}. ${cheer}`,
      cheers: ['Great detective work!', 'You cracked it!', 'Brilliant!', 'Case closed!', 'Sharp eyes!', 'Top secret agent!'],
      notThisTime: full => `Not this time — it was ${full}.`,
      keepGoing: 'Keep going — the next case is a fresh start!',
      jsonSummary: 'Puzzle JSON (for grown-ups and developers)',
      next: 'Next case ➜',
      stats: (solved, played, stars, best) => `🗂️ Cases solved: ${solved} of ${played} · ⭐ Stars: ${stars} · 🔥 Best streak: ${best}`,
      reset: 'Reset progress', resetConfirm: 'Reset all stars and streaks?',
      guideTitle: '📖 Cipher guide', guideClose: 'Close guide',
      guideSteps: A => [
        'Turn on the <b>🔍 Magnifier</b> to see how many steps each letter moved.',
        `<b>Are all the steps the same?</b> Yes → <b>Caesar</b> (or <b>${rot(A)}</b> if they are all ${A.half}).`,
        `<b>Do the letters mirror?</b> ${mir3(A)} → <b>Atbash</b>.`,
        '<b>Do the steps repeat in a cycle</b> of 3 or 4? → <b>Vigenère</b>.',
        '<b>Does the same letter always become the same code letter</b>, but the steps jump around? → <b>Affine</b>.',
        '<b>Same letter, different code letters, and no cycle?</b> → <b>Beaufort</b>.'],
      letterNumbers: 'Letter numbers:', howToSpot: 'How to spot it: ',
    },
    sheet: {
      appTitle: '🕵️ Cipher Detective — Printable worksheet',
      appSub: 'Seed-based A4 worksheets: a message and its secret code, tick which cipher was used. Optional guide and answer-key pages.',
      allPuzzles: '🧩 All puzzles', playOnline: '🎮 Play online',
      seed: 'Seed', seedHint: 'Same seed + same level ⇒ identical worksheet.', randomSeed: 'Random seed',
      level: 'Level', easyN: 'Easy · 3 ciphers', hardN: 'Hard · 6 ciphers',
      msgLang: 'Message language', msgLangHint: 'Alphabet and secret messages in this language; the texts follow the flag at the top.',
      cases: 'Cases', casesHint: 'About 6 fit on one page; more spill onto extra pages.',
      options: 'Options', optSteps: 'Step boxes for counting the shift', optHints: 'Hints, printed upside-down at the bottom',
      optGuide: "Detective's guide page", optKey: 'Answer key page',
      optAlpha: 'Alphabet strip for counting (help for younger kids)',
      newWorksheet: 'New worksheet', print: 'Print / Save PDF',
      casesCount: n => `${n} case${n === 1 ? '' : 's'}`, pagesCount: n => `${n} page${n === 1 ? '' : 's'}`,
      partSheet: 'worksheet', partGuide: 'guide', partKey: 'answer key',
      genError: 'Could not generate: ',
      sheetTitle: '🕵️ Cipher Detective',
      sheetSub: (level, n) => `${level} · ${n} case${n === 1 ? '' : 's'} · which cipher did the spy use?`,
      seedLabel: 'seed:', name: 'Name:', date: 'Date:',
      instr: 'Each message was sent in secret code. Compare the message (white) with its code (grey), work out which cipher the spy used, and tick it.',
      instrSteps: A => ` Count how many steps each letter moved forward (${L(A, 0)}→${L(A, 1)} is 1, wrapping around after ${last(A)}) and write it in the small boxes.`,
      caseN: i => `Case ${i}`, hintsFlip: 'Hints (turn the page upside down)',
      guideTitle: "📖 Detective's guide", guideSub: level => `${level} · how to tell the ciphers apart`,
      checklist: A => [
        `Count how many steps each letter moved forward in the alphabet (${L(A, 0)}→${L(A, 1)} is 1, wrapping around after ${last(A)}) and write it under the code letter.`,
        `<b>Are all the steps the same?</b> Yes → <b>Caesar</b>. If they are all ${A.half} → <b>${rot(A)}</b>.`,
        `<b>Do the letters mirror?</b> ${mir3(A)} (letter number + code number = ${A.n - 1}) → <b>Atbash</b>.`,
        '<b>Do the steps repeat in a cycle</b> of 3 or 4? → <b>Vigenère</b>.',
        '<b>Does the same letter always become the same code letter</b>, but the steps jump around with no cycle? → <b>Affine</b>.',
        '<b>Same letter, different code letters, and no cycle?</b> → <b>Beaufort</b>.'],
      keyTitle: '🔑 Answer key', keySub: (level, n) => `${level} · ${n} cases · numbers show how many steps each letter moved`,
      howToSpot: 'How to spot it:',
    },
  };

  /* ======================================================================== PL */
  T.pl = {
    levels: { easy: 'Łatwy', hard: 'Trudny' },
    guide: { sample: 'CZEŚĆ SZPIEGU', key: 'KOT' },
    ciphers: {
      caesar: {
        name: 'Cezar', full: 'szyfr Cezara',
        blurb: 'Każda litera przesuwa się o tyle samo miejsc.',
        how: A => `Wybierz liczbę (przesunięcie). Przesuń każdą literę o tyle miejsc do przodu w alfabecie. Po ${last(A)} wracasz do ${L(A, 0)}.`,
        spot: A => `Wszystkie liczby kroków są takie same — ale nie ${A.half} (${A.half} to ${rot(A)}).`,
        hints: ({ shift }, ex) => [
          'Spójrz na pierwszą literę. Policz, o ile miejsc przesunęła się w alfabecie. Teraz sprawdź następną — czy to ta sama liczba?',
          `Każda litera przesunęła się dokładnie o ${shift} miejsc do przodu. ${ex.p} zmieniło się w ${ex.c}.`],
        explain: ({ shift }, ex) => `To był szyfr Cezara z przesunięciem ${shift}, więc ${ex.p} zmieniło się w ${ex.c}. Każda litera przesunęła się o te same ${shift} miejsc.`,
      },
      rot13: {
        name: A => rot(A), full: A => rot(A),
        blurb: A => `Każda litera przesuwa się o ${A.half} miejsc — ${even(A) ? '' : 'prawie '}pół alfabetu.`,
        how: A => `Szyfr Cezara z przesunięciem dokładnie ${A.half}. ${even(A) ? `Ponieważ ${A.half} to połowa z ${A.n} liter, zrobienie tego dwa razy przywraca każdą literę.` : `To mniej więcej połowa z ${A.n} liter alfabetu.`}`,
        spot: A => `Każda liczba kroków to ${A.half}. ${rotPair(A)}.`,
        hints: (_, ex, A) => [
          'Każda litera przesunęła się o tyle samo miejsc. Czy to duży skok — mniej więcej pół alfabetu?',
          `Każda litera przesunęła się o ${A.half} miejsc, ${even(A) ? 'dokładnie' : 'prawie'} pół alfabetu. ${ex.p} zmieniło się w ${ex.c}.${even(A) ? ` Przesuń o kolejne ${A.half} i wracasz do początku!` : ''}`],
        explain: (_, ex, A) => `To był ${rot(A)}: każda litera przesunęła się o ${A.half} miejsc, ${even(A) ? '' : 'prawie '}pół alfabetu, więc ${ex.p} zmieniło się w ${ex.c}.${even(A) ? ' Zrobienie tego dwa razy przywraca literę.' : ''}`,
      },
      atbash: {
        name: 'Atbasz', full: 'Atbasz',
        blurb: A => `Alfabet jest odwrócony: ${mir(A, 0)}, ${mir(A, 1)}.`,
        how: A => `Napisz alfabet od początku, a pod nim od końca. Każda litera zmienia się w tę pod spodem: ${mir3(A)}.`,
        spot: A => `Liczby kroków są różne, ale litera i jej szyfr są lustrzanym odbiciem: pierwsza litera (${L(A, 0)}) staje się ostatnią (${last(A)}), druga (${L(A, 1)}) — przedostatnią (${last(A, 1)}).`,
        hints: (_, ex, A) => [
          `Spróbuj przeczytać alfabet od tyłu. W co zmieniłoby się ${L(A, 0)}?`,
          `Alfabet jest odbity w lustrze: ${mir3(A)}. Tutaj ${ex.p} zmieniło się w ${ex.c}.`],
        explain: (_, ex, A) => `To był Atbasz: alfabet jest odwrócony, więc ${mir(A, 0)} i ${mir(A, 1)}. Tutaj ${ex.p} zmieniło się w ${ex.c}.`,
      },
      vigenere: {
        name: 'Vigenère', full: 'szyfr Vigenère\'a',
        blurb: 'Słowo-klucz daje każdej literze inne przesunięcie, w kółko.',
        how: A => `Wybierz słowo-klucz. Jego litery to przesunięcia (${numbering(A)}). Pierwsza litera wiadomości przesuwa się o pierwszą literę klucza, druga o drugą, a klucz się powtarza.`,
        spot: 'Liczby kroków powtarzają się w krótkim cyklu co 3 lub 4 litery.',
        hints: ({ key }, ex, A) => [
          'Kroki zmieniają się z litery na literę. Ale przyjrzyj się — czy po chwili wracają i się powtarzają?',
          `Kroki powtarzają się co ${[...key].length} litery: ${nums(key, A)}. To słowo-klucz ${key} dodane do wiadomości.`],
        explain: ({ key }, ex, A) => `To był szyfr Vigenère'a ze słowem-kluczem ${key}. Każda litera przesuwa się o swoją literę klucza: ${ex.p} + ${k0(key)} (${A.idx(k0(key))} kroków) → ${ex.c}. Klucz powtarza się co ${[...key].length} litery.`,
      },
      affine: {
        name: 'Afiniczny', full: 'szyfr afiniczny',
        blurb: 'Numer każdej litery jest mnożony, a potem przesuwany.',
        how: A => `Zamień literę na liczbę (${range(A)}). Pomnóż przez a, dodaj b i zawiń po ${A.n}. Zamień liczbę z powrotem na literę.`,
        spot: 'Ta sama litera zawsze zmienia się w tę samą literę szyfru, ale liczby kroków skaczą bez cyklu i bez lustra.',
        hints: ({ a, b }, ex, A) => [
          'Ta sama litera zawsze zmienia się w tę samą literę szyfru — ale kroki skaczą bez żadnego cyklu.',
          `Numer każdej litery (${range(A)}) został pomnożony przez ${a}, a potem dodano ${b}.`],
        explain: ({ a, b }, ex, A) => `To był szyfr afiniczny: numer każdej litery pomnożono przez ${a}, a potem dodano ${b}. ${ex.p} to ${ex.pn}: ${a} × ${ex.pn} + ${b} = ${a * ex.pn + b}, zawinięte po ${A.n} → ${mod(a * ex.pn + b, A.n)}, czyli ${ex.c}.`,
      },
      beaufort: {
        name: 'Beaufort', full: 'szyfr Beauforta',
        blurb: 'Słowo-klucz, ale liczysz do tyłu od litery klucza.',
        how: A => `Wybierz słowo-klucz. Dla każdej litery wiadomości zacznij od litery klucza i policz do tyłu o numer litery wiadomości (${L(A, 0)}=0, ${L(A, 1)}=1 …). Klucz się powtarza.`,
        spot: 'Ta sama litera może zmienić się w różne litery szyfru, a liczby kroków nie powtarzają się w cyklu.',
        hints: ({ key }) => [
          'Jest tu słowo-klucz — ale litery liczy się do tyłu od klucza, nie do przodu.',
          `Słowo-klucz to ${key}. Każda litera szyfru = litera klucza − litera wiadomości (licz do tyłu, zawijając).`],
        explain: ({ key }, ex, A) => `To był szyfr Beauforta ze słowem-kluczem ${key}. Licz do tyłu od litery klucza: ${k0(key)} (${A.idx(k0(key))}) − ${ex.p} (${ex.pn}) = ${mod(A.idx(k0(key)) - ex.pn, A.n)}, czyli ${ex.c}.`,
      },
    },
    whyNot: {
      closeRot13: half => `Blisko! ROT${half} to specjalny szyfr Cezara, który przesuwa dokładnie o ${half} miejsc — w tej grze liczy się jako osobny szyfr.`,
      closeCaesar: (s, half) => `Blisko! Każda litera rzeczywiście przesunęła się o tyle samo miejsc — ale o ${s}, nie o ${half}.`,
      stepsDiffer: (g, a, b) => `To nie ${g}: kroki nie są wszędzie takie same. ${a.p}→${a.c} to ${a.s} kroków, ale ${b.p}→${b.c} to ${b.s}.`,
      notMirror: (p, m, c) => `To nie Atbasz: w Atbaszu ${p} zmieniłoby się w ${m}, a tutaj zmieniło się w ${c}.`,
      sameLetterDiff: (g, p, c1, c2) => `To nie ${g}: ta sama litera ${p} raz zmieniła się w ${c1}, a innym razem w ${c2}. Tak dzieje się tylko ze słowem-kluczem.`,
      sameShift: (g, s, affine) => `To nie ${g}: każda litera przesunęła się o te same ${s} kroków. ${affine ? 'W szyfrze afinicznym kroki skaczą.' : 'Słowo-klucz zmieniałoby kroki.'}`,
      mirrored: g => `To nie ${g}: każda litera i jej szyfr są lustrzanym odbiciem (pierwsza ↔ ostatnia litera alfabetu). To wzór Atbasza.`,
      monoClue: 'Wskazówka: tutaj każda litera zawsze zmieniała się w tę samą literę szyfru — znak, że nie było zmieniającego się słowa-klucza.',
      cycle: (n, ns) => `To nie szyfr Beauforta: kroki powtarzają się w cyklu co ${n} (${ns}). To słowo-klucz dodawane do przodu — Vigenère.`,
      noCycle: 'To nie szyfr Vigenère\'a: kroki nie powtarzają się w cyklu. Ze słowem-kluczem dodawanym do przodu by się powtarzały.',
      keyFallback: (g, key) => `To nie ${g}: ten szyfr używał słowa-klucza ${key}, więc kroki idą za kluczem.`,
    },
    params: { shift: s => `przesunięcie ${s}`, key: k => `klucz ${k}`, affine: (a, b) => `a = ${a}, b = ${b}` },
    game: {
      allPuzzles: '🧩 Wszystkie zagadki', printWorksheet: '🖨️ Karty pracy',
      starsTitle: 'Gwiazdki razem', streakTitle: 'Obecna seria',
      msgLang: 'Język wiadomości:',
      caseTitle: n => `Zagadka nr ${n}`,
      lead: 'Szpieg wysłał tę wiadomość szyfrem. Porównaj wiadomość z szyfrem i odgadnij, jakiego szyfru użyto.',
      legendMessage: 'Wiadomość', legendCode: 'Szyfr', legendMag: '🔍 O ile miejsc przesunęła się litera',
      magnote: A => `Liczby pokazują, o ile miejsc każda litera przesunęła się do przodu w alfabecie (${L(A, 0)}→${L(A, 1)} to 1, po ${last(A)} zaczyna się od ${L(A, 0)}).`,
      hintBtn: n => `💡 Podpowiedź (jeszcze ${n})`, noHints: '💡 Brak podpowiedzi', magnifier: '🔍 Lupa', guide: '📖 Przewodnik po szyfrach',
      alphabet: '🔤 Alfabet', alphaNote: 'Dotknij litery w wiadomości, żeby zobaczyć jej skok na alfabecie.',
      alphaJump: (p, c, s) => `${p} → ${c}: ${s} ${slav(s, 'miejsce', 'miejsca', 'miejsc')} do przodu`,
      hintLabel: i => `💡 Podpowiedź ${i}:`,
      whichCipher: 'Jakiego szyfru użyto?',
      correct: (full, cheer) => `🎉 Brawo! To był ${full}. ${cheer}`,
      cheers: ['Świetna robota, detektywie!', 'Szyfr złamany!', 'Genialnie!', 'Sprawa zamknięta!', 'Bystre oko!', 'Tajny agent na medal!'],
      notThisTime: full => `Tym razem nie — to był ${full}.`,
      keepGoing: 'Nie poddawaj się — następna zagadka to nowy start!',
      jsonSummary: 'JSON zagadki (dla dorosłych i programistów)',
      next: 'Następna zagadka ➜',
      stats: (solved, played, stars, best) => `🗂️ Rozwiązane: ${solved} z ${played} · ⭐ Gwiazdki: ${stars} · 🔥 Najlepsza seria: ${best}`,
      reset: 'Wyzeruj postępy', resetConfirm: 'Wyzerować wszystkie gwiazdki i serie?',
      guideTitle: '📖 Przewodnik po szyfrach', guideClose: 'Zamknij przewodnik',
      guideSteps: A => [
        'Włącz <b>🔍 Lupę</b>, żeby zobaczyć, o ile miejsc przesunęła się każda litera.',
        `<b>Czy wszystkie kroki są takie same?</b> Tak → <b>Cezar</b> (albo <b>${rot(A)}</b>, jeśli wszystkie to ${A.half}).`,
        `<b>Czy litery są odbite w lustrze?</b> ${mir3(A)} → <b>Atbasz</b>.`,
        '<b>Czy kroki powtarzają się w cyklu</b> co 3 lub 4? → <b>Vigenère</b>.',
        '<b>Czy ta sama litera zawsze zmienia się w tę samą literę szyfru</b>, ale kroki skaczą? → <b>Afiniczny</b>.',
        '<b>Ta sama litera, różne litery szyfru i brak cyklu?</b> → <b>Beaufort</b>.'],
      letterNumbers: 'Numery liter:', howToSpot: 'Jak go rozpoznać: ',
    },
    sheet: {
      appTitle: '🕵️ Detektyw szyfrów — karty pracy do druku',
      appSub: 'Karty pracy A4 generowane z ziarna: wiadomość i jej tajny szyfr, zaznacz, jakiego szyfru użyto. Opcjonalnie strona z przewodnikiem i odpowiedzi.',
      allPuzzles: '🧩 Wszystkie zagadki', playOnline: '🎮 Zagraj online',
      seed: 'Ziarno', seedHint: 'To samo ziarno + ten sam poziom ⇒ identyczna karta pracy.', randomSeed: 'Losowe ziarno',
      level: 'Poziom', easyN: 'Łatwy · 3 szyfry', hardN: 'Trudny · 6 szyfrów',
      msgLang: 'Język wiadomości', msgLangHint: 'Alfabet i tajne wiadomości w tym języku; teksty w języku flagi u góry.',
      cases: 'Zagadki', casesHint: 'Około 6 mieści się na jednej stronie; więcej przechodzi na kolejne.',
      options: 'Opcje', optSteps: 'Kratki na liczenie przesunięcia', optHints: 'Podpowiedzi, wydrukowane do góry nogami na dole',
      optGuide: 'Strona z przewodnikiem detektywa', optKey: 'Strona z odpowiedziami',
      optAlpha: 'Alfabet do liczenia (pomoc dla młodszych dzieci)',
      newWorksheet: 'Nowa karta pracy', print: 'Drukuj / Zapisz PDF',
      casesCount: n => slav(n, '1 zagadka', `${n} zagadki`, `${n} zagadek`), pagesCount: n => slav(n, '1 strona', `${n} strony`, `${n} stron`),
      partSheet: 'karta pracy', partGuide: 'przewodnik', partKey: 'odpowiedzi',
      genError: 'Nie udało się wygenerować: ',
      sheetTitle: '🕵️ Detektyw szyfrów',
      sheetSub: (level, n) => `${level} · ${slav(n, '1 zagadka', `${n} zagadki`, `${n} zagadek`)} · jakiego szyfru użył szpieg?`,
      seedLabel: 'ziarno:', name: 'Imię:', date: 'Data:',
      instr: 'Każda wiadomość została wysłana tajnym szyfrem. Porównaj wiadomość (białe kratki) z szyfrem (szare), odgadnij, jakiego szyfru użył szpieg, i zaznacz go.',
      instrSteps: A => ` Policz, o ile miejsc przesunęła się każda litera do przodu w alfabecie (${L(A, 0)}→${L(A, 1)} to 1, po ${last(A)} zaczynasz od ${L(A, 0)}) i wpisz to w małe kratki.`,
      caseN: i => `Zagadka ${i}`, hintsFlip: 'Podpowiedzi (odwróć kartkę do góry nogami)',
      guideTitle: '📖 Przewodnik detektywa', guideSub: level => `${level} · jak rozpoznać szyfry`,
      checklist: A => [
        `Policz, o ile miejsc przesunęła się każda litera do przodu w alfabecie (${L(A, 0)}→${L(A, 1)} to 1, po ${last(A)} zaczynasz od ${L(A, 0)}) i wpisz to pod literą szyfru.`,
        `<b>Czy wszystkie kroki są takie same?</b> Tak → <b>Cezar</b>. Jeśli wszystkie to ${A.half} → <b>${rot(A)}</b>.`,
        `<b>Czy litery są odbite w lustrze?</b> ${mir3(A)} (numer litery + numer szyfru = ${A.n - 1}) → <b>Atbasz</b>.`,
        '<b>Czy kroki powtarzają się w cyklu</b> co 3 lub 4? → <b>Vigenère</b>.',
        '<b>Czy ta sama litera zawsze zmienia się w tę samą literę szyfru</b>, ale kroki skaczą bez cyklu? → <b>Afiniczny</b>.',
        '<b>Ta sama litera, różne litery szyfru i brak cyklu?</b> → <b>Beaufort</b>.'],
      keyTitle: '🔑 Odpowiedzi', keySub: (level, n) => `${level} · ${slav(n, '1 zagadka', `${n} zagadki`, `${n} zagadek`)} · liczby pokazują, o ile miejsc przesunęła się każda litera`,
      howToSpot: 'Jak go rozpoznać:',
    },
  };

  /* ======================================================================== UK */
  T.uk = {
    levels: { easy: 'Легкий', hard: 'Складний' },
    guide: { sample: 'ПРИВІТ ШПИГУНЕ', key: 'КІТ' },
    ciphers: {
      caesar: {
        name: 'Цезар', full: 'шифр Цезаря',
        blurb: 'Кожна літера зсувається на однакову кількість кроків.',
        how: A => `Вибери число (зсув). Зсунь кожну літеру на стільки кроків уперед за абеткою. Після ${last(A)} повертайся до ${L(A, 0)}.`,
        spot: A => `Усі числа кроків однакові — але не ${A.half} (${A.half} — це ${rot(A)}).`,
        hints: ({ shift }, ex) => [
          'Подивись на першу літеру. Порахуй, на скільки кроків вона зсунулася за абеткою. Тепер перевір наступну — це те саме число?',
          `Кожна літера зсунулася рівно на ${shift} кроків уперед. ${ex.p} стало ${ex.c}.`],
        explain: ({ shift }, ex) => `Це був шифр Цезаря зі зсувом ${shift}, тому ${ex.p} стало ${ex.c}. Кожна літера зсунулася на ті самі ${shift} кроків.`,
      },
      rot13: {
        name: A => rot(A), full: A => rot(A),
        blurb: A => `Кожна літера зсувається на ${A.half} кроків — ${even(A) ? '' : 'майже '}пів абетки.`,
        how: A => `Шифр Цезаря зі зсувом рівно ${A.half}. ${even(A) ? `Оскільки ${A.half} — половина від ${A.n}, якщо зробити це двічі, кожна літера повернеться назад.` : `Це приблизно половина з ${A.n} літер абетки.`}`,
        spot: A => `Кожне число кроків — ${A.half}. ${rotPair(A)}.`,
        hints: (_, ex, A) => [
          'Кожна літера зсунулася на однакову кількість кроків. Це великий стрибок — приблизно пів абетки?',
          `Кожна літера зсунулася на ${A.half} кроків, ${even(A) ? 'рівно' : 'майже'} пів абетки. ${ex.p} стало ${ex.c}.${even(A) ? ` Зсунь ще на ${A.half} — і повернешся назад!` : ''}`],
        explain: (_, ex, A) => `Це був ${rot(A)}: кожна літера зсунулася на ${A.half} кроків, ${even(A) ? '' : 'майже '}пів абетки, тому ${ex.p} стало ${ex.c}.${even(A) ? ' Якщо зробити це двічі, літера повертається.' : ''}`,
      },
      atbash: {
        name: 'Атбаш', full: 'Атбаш',
        blurb: A => `Абетка перевернута: ${mir(A, 0)}, ${mir(A, 1)}.`,
        how: A => `Напиши абетку спочатку, а під нею — з кінця. Кожна літера стає тією, що під нею: ${mir3(A)}.`,
        spot: A => `Числа кроків різні, але літера та її шифр — дзеркальні: перша літера (${L(A, 0)}) стає останньою (${last(A)}), друга (${L(A, 1)}) — передостанньою (${last(A, 1)}).`,
        hints: (_, ex, A) => [
          `Спробуй прочитати абетку з кінця. На що перетворилося б ${L(A, 0)}?`,
          `Абетка віддзеркалена: ${mir3(A)}. Тут ${ex.p} стало ${ex.c}.`],
        explain: (_, ex, A) => `Це був Атбаш: абетка перевернута, тому ${mir(A, 0)} і ${mir(A, 1)}. Тут ${ex.p} стало ${ex.c}.`,
      },
      vigenere: {
        name: 'Віженер', full: 'шифр Віженера',
        blurb: 'Ключове слово дає кожній літері свій зсув, по колу.',
        how: A => `Вибери ключове слово. Його літери — це зсуви (${numbering(A)}). Перша літера повідомлення зсувається на першу літеру ключа, друга — на другу, а ключ повторюється.`,
        spot: 'Числа кроків повторюються коротким циклом із 3 або 4.',
        hints: ({ key }, ex, A) => [
          'Кроки змінюються від літери до літери. Але придивись — чи повертаються вони й повторюються?',
          `Кроки повторюються кожні ${[...key].length} літери: ${nums(key, A)}. Це ключове слово ${key}, додане до повідомлення.`],
        explain: ({ key }, ex, A) => `Це був шифр Віженера з ключовим словом ${key}. Кожна літера зсувається на свою літеру ключа: ${ex.p} + ${k0(key)} (${A.idx(k0(key))} кроків) → ${ex.c}. Ключ повторюється кожні ${[...key].length} літери.`,
      },
      affine: {
        name: 'Афінний', full: 'афінний шифр',
        blurb: 'Номер кожної літери множать, а потім зсувають.',
        how: A => `Перетвори літеру на число (${range(A)}). Помнож на a, додай b і візьми остачу від ділення на ${A.n}. Перетвори число назад на літеру.`,
        spot: 'Та сама літера завжди стає тією самою літерою шифру, але числа кроків стрибають без циклу й без дзеркала.',
        hints: ({ a, b }, ex, A) => [
          'Та сама літера завжди перетворюється на ту саму літеру шифру — але кроки стрибають без жодного циклу.',
          `Номер кожної літери (${range(A)}) помножили на ${a}, а потім додали ${b}.`],
        explain: ({ a, b }, ex, A) => `Це був афінний шифр: номер кожної літери помножили на ${a}, а потім додали ${b}. ${ex.p} — це ${ex.pn}: ${a} × ${ex.pn} + ${b} = ${a * ex.pn + b}, остача від ${A.n} → ${mod(a * ex.pn + b, A.n)}, тобто ${ex.c}.`,
      },
      beaufort: {
        name: 'Бофор', full: 'шифр Бофора',
        blurb: 'Ключове слово, але рахуєш назад від літери ключа.',
        how: A => `Вибери ключове слово. Для кожної літери повідомлення почни з літери ключа й відрахуй назад номер літери повідомлення (${L(A, 0)}=0, ${L(A, 1)}=1 …). Ключ повторюється.`,
        spot: 'Та сама літера може стати різними літерами шифру, а числа кроків не повторюються циклом.',
        hints: ({ key }) => [
          'Тут є ключове слово — але літери рахують назад від ключа, а не вперед.',
          `Ключове слово — ${key}. Кожна літера шифру = літера ключа − літера повідомлення (рахуй назад, по колу).`],
        explain: ({ key }, ex, A) => `Це був шифр Бофора з ключовим словом ${key}. Рахуй назад від літери ключа: ${k0(key)} (${A.idx(k0(key))}) − ${ex.p} (${ex.pn}) = ${mod(A.idx(k0(key)) - ex.pn, A.n)}, тобто ${ex.c}.`,
      },
    },
    whyNot: {
      closeRot13: half => `Майже! ROT${half} — це особливий шифр Цезаря, що зсуває рівно на ${half} кроків. У цій грі він рахується окремим шифром.`,
      closeCaesar: (s, half) => `Близько! Кожна літера справді зсунулася на однакову кількість кроків — але на ${s}, а не на ${half}.`,
      stepsDiffer: (g, a, b) => `Це не ${g}: кроки не всюди однакові. ${a.p}→${a.c} — це ${a.s} кроків, а ${b.p}→${b.c} — ${b.s}.`,
      notMirror: (p, m, c) => `Це не Атбаш: в Атбаші ${p} стало б ${m}, а тут воно стало ${c}.`,
      sameLetterDiff: (g, p, c1, c2) => `Це не ${g}: та сама літера ${p} один раз стала ${c1}, а іншим разом — ${c2}. Так буває лише з ключовим словом.`,
      sameShift: (g, s, affine) => `Це не ${g}: кожна літера зсунулася на ті самі ${s} кроків. ${affine ? 'В афінному шифрі кроки стрибають.' : 'Ключове слово змінювало б кроки.'}`,
      mirrored: g => `Це не ${g}: кожна літера та її шифр — дзеркальні (перша ↔ остання літера абетки). Це схема Атбаша.`,
      monoClue: 'Підказка: тут кожна літера завжди ставала тією самою літерою шифру — знак, що змінного ключового слова не було.',
      cycle: (n, ns) => `Це не шифр Бофора: кроки повторюються циклом із ${n} (${ns}). Це ключове слово, додане вперед, — Віженер.`,
      noCycle: 'Це не шифр Віженера: кроки не повторюються циклом. З ключовим словом, доданим уперед, вони б повторювалися.',
      keyFallback: (g, key) => `Це не ${g}: цей шифр використовував ключове слово ${key}, тож кроки йдуть за ключем.`,
    },
    params: { shift: s => `зсув ${s}`, key: k => `ключ ${k}`, affine: (a, b) => `a = ${a}, b = ${b}` },
    game: {
      allPuzzles: '🧩 Усі головоломки', printWorksheet: '🖨️ Робочі аркуші',
      starsTitle: 'Усього зірок', streakTitle: 'Поточна серія',
      msgLang: 'Мова повідомлення:',
      caseTitle: n => `Справа №${n}`,
      lead: 'Шпигун надіслав це повідомлення шифром. Порівняй повідомлення з шифром і визнач, який шифр використано.',
      legendMessage: 'Повідомлення', legendCode: 'Шифр', legendMag: '🔍 На скільки кроків зсунулася літера',
      magnote: A => `Числа показують, на скільки кроків уперед зсунулася кожна літера (${L(A, 0)}→${L(A, 1)} — це 1, після ${last(A)} починається ${L(A, 0)}).`,
      hintBtn: n => `💡 Підказка (ще ${n})`, noHints: '💡 Підказок більше немає', magnifier: '🔍 Лупа', guide: '📖 Довідник шифрів',
      alphabet: '🔤 Абетка', alphaNote: 'Торкнись літери в повідомленні, щоб побачити її стрибок на абетці.',
      alphaJump: (p, c, s) => `${p} → ${c}: ${s} ${slav(s, 'крок', 'кроки', 'кроків')} уперед`,
      hintLabel: i => `💡 Підказка ${i}:`,
      whichCipher: 'Який шифр використано?',
      correct: (full, cheer) => `🎉 Правильно! Це був ${full}. ${cheer}`,
      cheers: ['Чудова робота, детективе!', 'Шифр розгадано!', 'Блискуче!', 'Справу закрито!', 'Гостре око!', 'Справжній таємний агент!'],
      notThisTime: full => `Цього разу ні — це був ${full}.`,
      keepGoing: 'Не здавайся — наступна справа починається з чистого аркуша!',
      jsonSummary: 'JSON головоломки (для дорослих і розробників)',
      next: 'Наступна справа ➜',
      stats: (solved, played, stars, best) => `🗂️ Розв'язано: ${solved} з ${played} · ⭐ Зірки: ${stars} · 🔥 Найкраща серія: ${best}`,
      reset: 'Скинути прогрес', resetConfirm: 'Скинути всі зірки та серії?',
      guideTitle: '📖 Довідник шифрів', guideClose: 'Закрити довідник',
      guideSteps: A => [
        'Увімкни <b>🔍 Лупу</b>, щоб побачити, на скільки кроків зсунулася кожна літера.',
        `<b>Усі кроки однакові?</b> Так → <b>Цезар</b> (або <b>${rot(A)}</b>, якщо всі дорівнюють ${A.half}).`,
        `<b>Літери дзеркальні?</b> ${mir3(A)} → <b>Атбаш</b>.`,
        '<b>Кроки повторюються циклом</b> із 3 або 4? → <b>Віженер</b>.',
        '<b>Та сама літера завжди стає тією самою літерою шифру</b>, але кроки стрибають? → <b>Афінний</b>.',
        '<b>Та сама літера, різні літери шифру і без циклу?</b> → <b>Бофор</b>.'],
      letterNumbers: 'Номери літер:', howToSpot: 'Як його впізнати: ',
    },
    sheet: {
      appTitle: '🕵️ Детектив шифрів — робочі аркуші для друку',
      appSub: 'Аркуші A4, створені із зерна: повідомлення та його таємний шифр, познач, який шифр використано. За бажанням — сторінка з довідником і відповіді.',
      allPuzzles: '🧩 Усі головоломки', playOnline: '🎮 Грати онлайн',
      seed: 'Зерно', seedHint: 'Те саме зерно + той самий рівень ⇒ однаковий аркуш.', randomSeed: 'Випадкове зерно',
      level: 'Рівень', easyN: 'Легкий · 3 шифри', hardN: 'Складний · 6 шифрів',
      msgLang: 'Мова повідомлення', msgLangHint: 'Абетка й таємні повідомлення цією мовою; тексти — мовою прапорця вгорі.',
      cases: 'Справи', casesHint: 'Приблизно 6 вміщується на одній сторінці; решта переходить на наступні.',
      options: 'Параметри', optSteps: 'Клітинки для підрахунку зсуву', optHints: 'Підказки, надруковані догори дриґом унизу',
      optGuide: 'Сторінка з довідником детектива', optKey: 'Сторінка з відповідями',
      optAlpha: 'Абетка для підрахунку (допомога для молодших дітей)',
      newWorksheet: 'Новий аркуш', print: 'Друк / Зберегти PDF',
      casesCount: n => slav(n, '1 справа', `${n} справи`, `${n} справ`), pagesCount: n => slav(n, '1 сторінка', `${n} сторінки`, `${n} сторінок`),
      partSheet: 'аркуш', partGuide: 'довідник', partKey: 'відповіді',
      genError: 'Не вдалося створити: ',
      sheetTitle: '🕵️ Детектив шифрів',
      sheetSub: (level, n) => `${level} · ${slav(n, '1 справа', `${n} справи`, `${n} справ`)} · який шифр використав шпигун?`,
      seedLabel: 'зерно:', name: 'Ім\'я:', date: 'Дата:',
      instr: 'Кожне повідомлення надіслано таємним шифром. Порівняй повідомлення (білі клітинки) з шифром (сірі), визнач, який шифр використав шпигун, і познач його.',
      instrSteps: A => ` Порахуй, на скільки кроків уперед зсунулася кожна літера (${L(A, 0)}→${L(A, 1)} — це 1, після ${last(A)} починай з ${L(A, 0)}), і запиши це в маленькі клітинки.`,
      caseN: i => `Справа ${i}`, hintsFlip: 'Підказки (переверни аркуш догори дриґом)',
      guideTitle: '📖 Довідник детектива', guideSub: level => `${level} · як розрізнити шифри`,
      checklist: A => [
        `Порахуй, на скільки кроків уперед за абеткою зсунулася кожна літера (${L(A, 0)}→${L(A, 1)} — це 1, після ${last(A)} починай з ${L(A, 0)}), і запиши це під літерою шифру.`,
        `<b>Усі кроки однакові?</b> Так → <b>Цезар</b>. Якщо всі дорівнюють ${A.half} → <b>${rot(A)}</b>.`,
        `<b>Літери дзеркальні?</b> ${mir3(A)} (номер літери + номер шифру = ${A.n - 1}) → <b>Атбаш</b>.`,
        '<b>Кроки повторюються циклом</b> із 3 або 4? → <b>Віженер</b>.',
        '<b>Та сама літера завжди стає тією самою літерою шифру</b>, але кроки стрибають без циклу? → <b>Афінний</b>.',
        '<b>Та сама літера, різні літери шифру і без циклу?</b> → <b>Бофор</b>.'],
      keyTitle: '🔑 Відповіді', keySub: (level, n) => `${level} · ${slav(n, '1 справа', `${n} справи`, `${n} справ`)} · числа показують, на скільки кроків зсунулася кожна літера`,
      howToSpot: 'Як його впізнати:',
    },
  };

  /* ======================================================================== VI */
  T.vi = {
    levels: { easy: 'Dễ', hard: 'Khó' },
    guide: { sample: 'CHAO ĐIÊP VIÊN', key: 'MEO' },
    ciphers: {
      caesar: {
        name: 'Caesar', full: 'mật mã Caesar',
        blurb: 'Mỗi chữ cái dịch đi cùng một số bước.',
        how: A => `Chọn một số (bước dịch). Dịch mỗi chữ cái tiến lên bấy nhiêu bước trong bảng chữ cái. Sau ${last(A)} thì quay lại ${L(A, 0)}.`,
        spot: A => `Tất cả các số bước đều giống nhau — nhưng không phải ${A.half} (${A.half} là ${rot(A)}).`,
        hints: ({ shift }, ex) => [
          'Nhìn chữ cái đầu tiên. Đếm xem nó dịch đi bao nhiêu bước trong bảng chữ cái. Rồi kiểm tra chữ tiếp theo — có cùng số không?',
          `Mỗi chữ cái dịch đúng ${shift} bước về phía trước. ${ex.p} trở thành ${ex.c}.`],
        explain: ({ shift }, ex) => `Đây là mật mã Caesar với bước dịch ${shift}, nên ${ex.p} trở thành ${ex.c}. Mỗi chữ cái đều dịch đi ${shift} bước như nhau.`,
      },
      rot13: {
        name: A => rot(A), full: A => rot(A),
        blurb: A => `Mỗi chữ cái dịch ${A.half} bước — ${even(A) ? '' : 'gần '}nửa bảng chữ cái.`,
        how: A => `Mật mã Caesar với bước dịch đúng bằng ${A.half}. ${even(A) ? `Vì ${A.half} là một nửa của ${A.n}, làm hai lần sẽ đưa mọi chữ cái về chỗ cũ.` : `Đó là khoảng một nửa của ${A.n} chữ cái.`}`,
        spot: A => `Mọi số bước đều là ${A.half}. ${rotPair(A)}.`,
        hints: (_, ex, A) => [
          'Mỗi chữ cái dịch đi cùng một số bước. Có phải là một bước nhảy lớn — khoảng nửa bảng chữ cái?',
          `Mỗi chữ cái dịch ${A.half} bước, ${even(A) ? 'đúng' : 'gần'} nửa bảng chữ cái. ${ex.p} trở thành ${ex.c}.${even(A) ? ` Dịch thêm ${A.half} bước nữa là quay về!` : ''}`],
        explain: (_, ex, A) => `Đây là ${rot(A)}: mỗi chữ cái dịch ${A.half} bước, ${even(A) ? '' : 'gần '}nửa bảng chữ cái, nên ${ex.p} trở thành ${ex.c}.${even(A) ? ' Làm hai lần sẽ đưa chữ cái về chỗ cũ.' : ''}`,
      },
      atbash: {
        name: 'Atbash', full: 'Atbash',
        blurb: A => `Bảng chữ cái bị lật ngược: ${mir(A, 0)}, ${mir(A, 1)}.`,
        how: A => `Viết bảng chữ cái xuôi, rồi viết ngược ở bên dưới. Mỗi chữ cái trở thành chữ ở ngay dưới nó: ${mir3(A)}.`,
        spot: A => `Các số bước khác nhau, nhưng chữ cái và chữ mã hóa là hình phản chiếu: chữ đầu (${L(A, 0)}) thành chữ cuối (${last(A)}), chữ thứ hai (${L(A, 1)}) thành chữ áp chót (${last(A, 1)}).`,
        hints: (_, ex, A) => [
          `Thử đọc bảng chữ cái ngược lại. ${L(A, 0)} sẽ trở thành gì?`,
          `Bảng chữ cái được phản chiếu: ${mir3(A)}. Ở đây ${ex.p} trở thành ${ex.c}.`],
        explain: (_, ex, A) => `Đây là Atbash: bảng chữ cái bị lật ngược, nên ${mir(A, 0)} và ${mir(A, 1)}. Ở đây ${ex.p} trở thành ${ex.c}.`,
      },
      vigenere: {
        name: 'Vigenère', full: 'mật mã Vigenère',
        blurb: 'Một từ khóa cho mỗi chữ cái một bước dịch riêng, lặp lại.',
        how: A => `Chọn một từ khóa. Các chữ cái của nó là các bước dịch (${numbering(A)}). Chữ cái đầu của tin nhắn dịch theo chữ đầu của khóa, chữ thứ hai theo chữ thứ hai, và khóa lặp lại.`,
        spot: 'Các số bước lặp lại theo một chu kỳ ngắn 3 hoặc 4.',
        hints: ({ key }, ex, A) => [
          'Các bước thay đổi từ chữ này sang chữ khác. Nhưng nhìn kỹ — chúng có quay lại và lặp lại không?',
          `Các bước lặp lại sau mỗi ${[...key].length} chữ cái: ${nums(key, A)}. Đó là từ khóa ${key} được cộng vào tin nhắn.`],
        explain: ({ key }, ex, A) => `Đây là mật mã Vigenère với từ khóa ${key}. Mỗi chữ cái dịch theo chữ khóa của nó: ${ex.p} + ${k0(key)} (${A.idx(k0(key))} bước) → ${ex.c}. Khóa lặp lại sau mỗi ${[...key].length} chữ cái.`,
      },
      affine: {
        name: 'Affine', full: 'mật mã Affine',
        blurb: 'Số của mỗi chữ cái được nhân lên, rồi dịch đi.',
        how: A => `Đổi chữ cái thành số (${range(A)}). Nhân với a, cộng b, rồi lấy phần dư khi chia cho ${A.n}. Đổi số trở lại thành chữ cái.`,
        spot: 'Cùng một chữ cái luôn thành cùng một chữ mã hóa, nhưng các số bước nhảy lung tung, không chu kỳ và không phản chiếu.',
        hints: ({ a, b }, ex, A) => [
          'Cùng một chữ cái luôn biến thành cùng một chữ mã hóa — nhưng các bước nhảy lung tung, không có chu kỳ.',
          `Số của mỗi chữ cái (${range(A)}) được nhân với ${a}, rồi cộng thêm ${b}.`],
        explain: ({ a, b }, ex, A) => `Đây là mật mã Affine: số của mỗi chữ cái được nhân với ${a}, rồi cộng thêm ${b}. ${ex.p} là ${ex.pn}: ${a} × ${ex.pn} + ${b} = ${a * ex.pn + b}, lấy dư cho ${A.n} → ${mod(a * ex.pn + b, A.n)}, tức là ${ex.c}.`,
      },
      beaufort: {
        name: 'Beaufort', full: 'mật mã Beaufort',
        blurb: 'Một từ khóa, nhưng bạn đếm lùi từ chữ khóa.',
        how: A => `Chọn một từ khóa. Với mỗi chữ cái của tin nhắn, bắt đầu từ chữ khóa và đếm lùi theo số của chữ cái tin nhắn (${L(A, 0)}=0, ${L(A, 1)}=1 …). Khóa lặp lại.`,
        spot: 'Cùng một chữ cái có thể thành những chữ mã hóa khác nhau, và các số bước không lặp lại theo chu kỳ.',
        hints: ({ key }) => [
          'Ở đây có một từ khóa — nhưng các chữ cái được đếm lùi từ khóa, không phải đếm tiến.',
          `Từ khóa là ${key}. Mỗi chữ mã hóa = chữ khóa − chữ tin nhắn (đếm lùi, quay vòng).`],
        explain: ({ key }, ex, A) => `Đây là mật mã Beaufort với từ khóa ${key}. Đếm lùi từ chữ khóa: ${k0(key)} (${A.idx(k0(key))}) − ${ex.p} (${ex.pn}) = ${mod(A.idx(k0(key)) - ex.pn, A.n)}, tức là ${ex.c}.`,
      },
    },
    whyNot: {
      closeRot13: half => `Suýt đúng! ROT${half} là một mật mã Caesar đặc biệt dịch đúng ${half} bước — trong trò chơi này nó được tính là một mật mã riêng.`,
      closeCaesar: (s, half) => `Gần đúng! Mỗi chữ cái đúng là dịch đi cùng một số bước — nhưng là ${s}, không phải ${half}.`,
      stepsDiffer: (g, a, b) => `Không phải ${g}: các bước không giống nhau hết. ${a.p}→${a.c} là ${a.s} bước, nhưng ${b.p}→${b.c} là ${b.s}.`,
      notMirror: (p, m, c) => `Không phải Atbash: trong Atbash, ${p} sẽ thành ${m}, nhưng ở đây nó thành ${c}.`,
      sameLetterDiff: (g, p, c1, c2) => `Không phải ${g}: cùng chữ ${p} có lúc thành ${c1}, lúc khác lại thành ${c2}. Điều đó chỉ xảy ra khi có từ khóa.`,
      sameShift: (g, s, affine) => `Không phải ${g}: mỗi chữ cái đều dịch cùng ${s} bước. ${affine ? 'Với Affine các bước nhảy lung tung.' : 'Một từ khóa sẽ làm các bước thay đổi.'}`,
      mirrored: g => `Không phải ${g}: mỗi chữ cái và chữ mã hóa của nó là hình phản chiếu (chữ đầu ↔ chữ cuối bảng chữ cái). Đó là kiểu Atbash.`,
      monoClue: 'Gợi ý: ở đây mỗi chữ cái luôn thành cùng một chữ mã hóa — dấu hiệu là không có từ khóa thay đổi.',
      cycle: (n, ns) => `Không phải mật mã Beaufort: các bước lặp lại theo chu kỳ ${n} (${ns}). Đó là từ khóa cộng tiến — Vigenère.`,
      noCycle: 'Không phải mật mã Vigenère: các bước không lặp lại theo chu kỳ. Nếu có từ khóa cộng tiến thì chúng sẽ lặp lại.',
      keyFallback: (g, key) => `Không phải ${g}: mật mã này dùng từ khóa ${key}, nên các bước đi theo khóa.`,
    },
    params: { shift: s => `dịch ${s}`, key: k => `khóa ${k}`, affine: (a, b) => `a = ${a}, b = ${b}` },
    game: {
      allPuzzles: '🧩 Tất cả câu đố', printWorksheet: '🖨️ Phiếu bài tập',
      starsTitle: 'Tổng số sao', streakTitle: 'Chuỗi hiện tại',
      msgLang: 'Ngôn ngữ tin nhắn:',
      caseTitle: n => `Vụ án số ${n}`,
      lead: 'Một điệp viên đã gửi tin nhắn này bằng mật mã. So sánh tin nhắn với bản mã và tìm ra mật mã nào đã được dùng.',
      legendMessage: 'Tin nhắn', legendCode: 'Mật mã', legendMag: '🔍 Số bước mỗi chữ cái dịch đi',
      magnote: A => `Các số cho biết mỗi chữ cái dịch tiến bao nhiêu bước (${L(A, 0)}→${L(A, 1)} là 1, sau ${last(A)} quay lại ${L(A, 0)}).`,
      hintBtn: n => `💡 Gợi ý (còn ${n})`, noHints: '💡 Hết gợi ý', magnifier: '🔍 Kính lúp', guide: '📖 Hướng dẫn mật mã',
      alphabet: '🔤 Bảng chữ cái', alphaNote: 'Chạm vào một chữ cái trong tin nhắn để thấy bước nhảy của nó trên bảng chữ cái.',
      alphaJump: (p, c, s) => `${p} → ${c}: ${s} bước về phía trước`,
      hintLabel: i => `💡 Gợi ý ${i}:`,
      whichCipher: 'Mật mã nào đã được dùng?',
      correct: (full, cheer) => `🎉 Đúng rồi! Đó là ${full}. ${cheer}`,
      cheers: ['Thám tử giỏi lắm!', 'Bạn đã giải được mã!', 'Xuất sắc!', 'Vụ án khép lại!', 'Mắt tinh thật!', 'Điệp viên hạng nhất!'],
      notThisTime: full => `Lần này chưa đúng — đó là ${full}.`,
      keepGoing: 'Cố lên — vụ án tiếp theo là một khởi đầu mới!',
      jsonSummary: 'JSON câu đố (dành cho người lớn và lập trình viên)',
      next: 'Vụ án tiếp theo ➜',
      stats: (solved, played, stars, best) => `🗂️ Đã giải: ${solved}/${played} · ⭐ Sao: ${stars} · 🔥 Chuỗi dài nhất: ${best}`,
      reset: 'Đặt lại tiến trình', resetConfirm: 'Đặt lại toàn bộ sao và chuỗi?',
      guideTitle: '📖 Hướng dẫn mật mã', guideClose: 'Đóng hướng dẫn',
      guideSteps: A => [
        'Bật <b>🔍 Kính lúp</b> để xem mỗi chữ cái dịch đi bao nhiêu bước.',
        `<b>Tất cả các bước có giống nhau không?</b> Có → <b>Caesar</b> (hoặc <b>${rot(A)}</b> nếu tất cả đều là ${A.half}).`,
        `<b>Các chữ cái có phản chiếu không?</b> ${mir3(A)} → <b>Atbash</b>.`,
        '<b>Các bước có lặp lại theo chu kỳ</b> 3 hoặc 4 không? → <b>Vigenère</b>.',
        '<b>Cùng một chữ cái có luôn thành cùng một chữ mã hóa</b>, nhưng các bước nhảy lung tung? → <b>Affine</b>.',
        '<b>Cùng chữ cái, khác chữ mã hóa, và không có chu kỳ?</b> → <b>Beaufort</b>.'],
      letterNumbers: 'Số của chữ cái:', howToSpot: 'Cách nhận ra: ',
    },
    sheet: {
      appTitle: '🕵️ Thám tử mật mã — phiếu bài tập để in',
      appSub: 'Phiếu bài tập A4 tạo từ mã hạt giống: tin nhắn và mật mã của nó, đánh dấu mật mã đã dùng. Có thể thêm trang hướng dẫn và trang đáp án.',
      allPuzzles: '🧩 Tất cả câu đố', playOnline: '🎮 Chơi trực tuyến',
      seed: 'Hạt giống', seedHint: 'Cùng hạt giống + cùng mức ⇒ phiếu giống hệt nhau.', randomSeed: 'Hạt giống ngẫu nhiên',
      level: 'Mức độ', easyN: 'Dễ · 3 mật mã', hardN: 'Khó · 6 mật mã',
      msgLang: 'Ngôn ngữ tin nhắn', msgLangHint: 'Bảng chữ cái và tin nhắn bí mật bằng ngôn ngữ này; phần chữ theo lá cờ ở trên.',
      cases: 'Số vụ án', casesHint: 'Khoảng 6 vụ vừa một trang; nhiều hơn sẽ sang trang tiếp.',
      options: 'Tùy chọn', optSteps: 'Ô trống để đếm bước dịch', optHints: 'Gợi ý, in ngược ở cuối trang',
      optGuide: 'Trang hướng dẫn thám tử', optKey: 'Trang đáp án',
      optAlpha: 'Bảng chữ cái để đếm (trợ giúp cho trẻ nhỏ)',
      newWorksheet: 'Phiếu mới', print: 'In / Lưu PDF',
      casesCount: n => `${n} vụ án`, pagesCount: n => `${n} trang`,
      partSheet: 'phiếu', partGuide: 'hướng dẫn', partKey: 'đáp án',
      genError: 'Không tạo được: ',
      sheetTitle: '🕵️ Thám tử mật mã',
      sheetSub: (level, n) => `${level} · ${n} vụ án · điệp viên đã dùng mật mã nào?`,
      seedLabel: 'hạt giống:', name: 'Tên:', date: 'Ngày:',
      instr: 'Mỗi tin nhắn được gửi bằng mật mã bí mật. So sánh tin nhắn (ô trắng) với mật mã (ô xám), tìm ra điệp viên đã dùng mật mã nào và đánh dấu.',
      instrSteps: A => ` Đếm xem mỗi chữ cái dịch tiến bao nhiêu bước (${L(A, 0)}→${L(A, 1)} là 1, sau ${last(A)} quay lại ${L(A, 0)}) và ghi vào các ô nhỏ.`,
      caseN: i => `Vụ án ${i}`, hintsFlip: 'Gợi ý (lật ngược trang)',
      guideTitle: '📖 Hướng dẫn thám tử', guideSub: level => `${level} · cách phân biệt các mật mã`,
      checklist: A => [
        `Đếm xem mỗi chữ cái dịch tiến bao nhiêu bước trong bảng chữ cái (${L(A, 0)}→${L(A, 1)} là 1, sau ${last(A)} quay lại ${L(A, 0)}) và viết số đó dưới chữ mã hóa.`,
        `<b>Tất cả các bước có giống nhau không?</b> Có → <b>Caesar</b>. Nếu tất cả đều là ${A.half} → <b>${rot(A)}</b>.`,
        `<b>Các chữ cái có phản chiếu không?</b> ${mir3(A)} (số chữ cái + số mã = ${A.n - 1}) → <b>Atbash</b>.`,
        '<b>Các bước có lặp lại theo chu kỳ</b> 3 hoặc 4 không? → <b>Vigenère</b>.',
        '<b>Cùng một chữ cái có luôn thành cùng một chữ mã hóa</b>, nhưng các bước nhảy lung tung, không chu kỳ? → <b>Affine</b>.',
        '<b>Cùng chữ cái, khác chữ mã hóa, và không có chu kỳ?</b> → <b>Beaufort</b>.'],
      keyTitle: '🔑 Đáp án', keySub: (level, n) => `${level} · ${n} vụ án · các số cho biết mỗi chữ cái dịch đi bao nhiêu bước`,
      howToSpot: 'Cách nhận ra:',
    },
  };

  if (typeof module !== 'undefined' && module.exports) module.exports = T;
})(typeof ENGINE !== 'undefined' ? ENGINE : require('./engine.js'));
